# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='messages.proto',
  package='qrcoder',
  serialized_pb='\n\x0emessages.proto\x12\x07qrcoder\"-\n\x0fQREncodeRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x02(\t\x12\x0c\n\x04size\x18\x02 \x01(\x05\"7\n\x10QREncodeResponse\x12\x12\n\nsuccessful\x18\x01 \x02(\x08\x12\x0f\n\x07qr_code\x18\x02 \x01(\x0c\" \n\x0fQRDecodeRequest\x12\r\n\x05image\x18\x01 \x02(\x0c\"4\n\x10QRDecodeResponse\x12\x12\n\nsuccessful\x18\x01 \x02(\x08\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\tB \n\x0f\x63om.cid.qrcoderB\rQRCoderProtos')




_QRENCODEREQUEST = descriptor.Descriptor(
  name='QREncodeRequest',
  full_name='qrcoder.QREncodeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='data', full_name='qrcoder.QREncodeRequest.data', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='size', full_name='qrcoder.QREncodeRequest.size', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=27,
  serialized_end=72,
)


_QRENCODERESPONSE = descriptor.Descriptor(
  name='QREncodeResponse',
  full_name='qrcoder.QREncodeResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='successful', full_name='qrcoder.QREncodeResponse.successful', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='qr_code', full_name='qrcoder.QREncodeResponse.qr_code', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=74,
  serialized_end=129,
)


_QRDECODEREQUEST = descriptor.Descriptor(
  name='QRDecodeRequest',
  full_name='qrcoder.QRDecodeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='image', full_name='qrcoder.QRDecodeRequest.image', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=131,
  serialized_end=163,
)


_QRDECODERESPONSE = descriptor.Descriptor(
  name='QRDecodeResponse',
  full_name='qrcoder.QRDecodeResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='successful', full_name='qrcoder.QRDecodeResponse.successful', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='data', full_name='qrcoder.QRDecodeResponse.data', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=165,
  serialized_end=217,
)

DESCRIPTOR.message_types_by_name['QREncodeRequest'] = _QRENCODEREQUEST
DESCRIPTOR.message_types_by_name['QREncodeResponse'] = _QRENCODERESPONSE
DESCRIPTOR.message_types_by_name['QRDecodeRequest'] = _QRDECODEREQUEST
DESCRIPTOR.message_types_by_name['QRDecodeResponse'] = _QRDECODERESPONSE

class QREncodeRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _QRENCODEREQUEST
  
  # @@protoc_insertion_point(class_scope:qrcoder.QREncodeRequest)

class QREncodeResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _QRENCODERESPONSE
  
  # @@protoc_insertion_point(class_scope:qrcoder.QREncodeResponse)

class QRDecodeRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _QRDECODEREQUEST
  
  # @@protoc_insertion_point(class_scope:qrcoder.QRDecodeRequest)

class QRDecodeResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _QRDECODERESPONSE
  
  # @@protoc_insertion_point(class_scope:qrcoder.QRDecodeResponse)

# @@protoc_insertion_point(module_scope)
